<a href="https://colab.research.google.com/github/masalad0sa/MACHINE_LEARNING/blob/main/Practical_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("ahmedmohamed2003/cafe-sales-dirty-data-for-cleaning-training")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'cafe-sales-dirty-data-for-cleaning-training' dataset.
Path to dataset files: /kaggle/input/cafe-sales-dirty-data-for-cleaning-training

In [ ]:
import pandas as pd
df = pd.read_csv(path + '/dirty_cafe_sales.csv')
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [ ]:
df[df.isnull().any(axis=1)]

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
5,TXN_2602893,Smoothie,5,4.0,20.0,Credit Card,NaN,2023-03-31
8,TXN_4717867,NaN,5,3.0,15.0,NaN,Takeaway,2023-07-28
9,TXN_2064365,Sandwich,5,4.0,20.0,NaN,In-store,2023-12-31
13,TXN_9437049,Cookie,5,1.0,5.0,NaN,Takeaway,2023-06-01
14,TXN_8915701,ERROR,2,1.5,3.0,NaN,In-store,2023-03-21
...,...,...,...,...,...,...,...,...
9994,TXN_7851634,UNKNOWN,4,4.0,16.0,NaN,NaN,2023-01-08
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02

In [ ]:
df =

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
25,TXN_7958992,Smoothie,3,4.0,NaN,UNKNOWN,UNKNOWN,2023-12-13
120,TXN_9790731,Cake,2,3.0,6.0,UNKNOWN,NaN,2023-06-02
145,TXN_8729570,Tea,5,1.5,7.5,UNKNOWN,In-store,2023-09-03
181,TXN_1136554,Smoothie,3,4.0,12.0,UNKNOWN,Takeaway,2023-03-26
...,...,...,...,...,...,...,...,...
9863,TXN_6017034,Cake,4,3.0,12.0,UNKNOWN,NaN,2023-10-06
9872,TXN_8318388,Cake,5,3.0,15.0,UNKNOWN,UNKNOWN,2023-11-26
9972,TXN_3124078,Cake,4,3.0,12.0,UNKNOWN,In-store,2023-08-06
9980,TXN_6796890,Tea,4,1.5,6.0,UNKNOWN,NaN,2023-08-24
9992,TXN_2739140,Smoothie,4,4.0,16.0,UNKNOWN,In-store,2023-07-05

In [ ]:
df['Payment Method'].value_counts()

Payment Method
Digital Wallet    2291
Credit Card       2273
Cash              2258
ERROR              306
UNKNOWN            293
Name: count, dtype: int64

In [ ]:
from sklearn.preprocessing import OneHotEncoder
X = df[['Payment Method']]
encoder= OneHotEncoder(drop='first', sparse_output=False)
encoder_df = pd.DataFrame(encoder.fit_transform(X))
encoder_df

        0    1    2    3    4
0     1.0  0.0  0.0  0.0  0.0
1     0.0  0.0  0.0  0.0  0.0
2     1.0  0.0  0.0  0.0  0.0
3     0.0  0.0  0.0  1.0  0.0
4     0.0  1.0  0.0  0.0  0.0
...   ...  ...  ...  ...  ...
9995  0.0  0.0  0.0  0.0  1.0
9996  0.0  1.0  0.0  0.0  0.0
9997  0.0  1.0  0.0  0.0  0.0
9998  0.0  1.0  0.0  0.0  0.0
9999  0.0  0.0  0.0  0.0  0.0

[10000 rows x 5 columns]

In [ ]:
encoded_features = encoder.fit_transform(X)

# 5. Convert the result back to a DataFrame and join with original data
encoder_df = pd.DataFrame(encoded_features, columns=encoder.get_feature_names_out(['Payment Method']))
df = pd.concat([df.reset_index(drop=True), encoder_df], axis=1)

# Display the result
df

,Transaction ID,Item,Quantity,Price Per Unit,Payment Method,Location,Transaction Date,Payment Method_Credit Card,Payment Method_Digital Wallet,Payment Method_ERROR,Payment Method_UNKNOWN,Payment Method_nan,Payment Method_Credit Card,Payment Method_Digital Wallet,Payment Method_ERROR,Payment Method_UNKNOWN,Payment Method_nan
0,TXN_1961373,Coffee,2,2.0,Credit Card,Takeaway,2023-09-08,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,TXN_4977031,Cake,4,3.0,Cash,In-store,2023-05-16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,TXN_4271903,Cookie,4,1.0,Credit Card,In-store,2023-07-19,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,TXN_7034554,Salad,2,5.0,UNKNOWN,UNKNOWN,2023-04-27,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
4,TXN_3160411,Coffee,2,2.0,Digital Wallet,In-store,2023-06-11,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,NaN,UNKNOWN,2023-08-30,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
9996,TXN_9659401,NaN,3,NaN,Digital Wallet,NaN,2023-06-02,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
9997,TXN_5255387,Coffee,4,2.0,Digital Wallet,NaN,2023-03-02,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
9998,TXN_7695629,Cookie,3,NaN,Digital Wallet,NaN,2023-12-02,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
9999,TXN_6170729,Sandwich,3,4.0,Cash,In-store,2023-11-07,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df['Total Items'] = scaler.fit_transform(df[['Total Items']])
df